### ISSUE TITLE
发现长时间运行有时会报一个token的错误

### ISSUE THREAD

**Issue by darkice1** [yiding-he/hydrogen-ssdb#28]
报错信息如下
```
[2020-02-28 03:01:40]java.lang.NullPointerException
CAUSE:null
        at com.hyd.ssdb.protocol.Request.readTokens(Request.java:71)
        at com.hyd.ssdb.protocol.Request.<init>(Request.java:37)
        at com.hyd.ssdb.AbstractClient.sendRequest(AbstractClient.java:94)
        at com.hyd.ssdb.SsdbClient.getBytes(SsdbClient.java:110)
        at tools.Ssdb.get(Ssdb.java:81)
        at tools.ssdb.SsdbReportLog.arrToLog(SsdbReportLog.java:28)
        at tools.ssdb.SsdbReportLog.reportToLog(SsdbReportLog.java:180)
        at tools.SsdbReports.main(SsdbReports.java:254)
```

**Comment by yiding-he** [comment]
根据堆栈信息，基本可以确定该错误的原因是在调用 `SsdbClient.getBytes(String key)` 方法时传入的参数值为 null 所致。我会更新代码以规避这个问题，但暂时不会发新版本。建议你这边加上相应的判断，不要传 null 值进来，然后继续观察一段时间看是否有所改善。

**Comment by darkice1** [comment]
ok
明白了

发自我的iPhone

**Comment by darkice1** [comment]
确认了 是传入null的问题
感谢感谢！
确实是应该使用sdk的人处理更好一些    sdk不用加验证影响性能
