### ISSUE TITLE
间歇性出现 NO CLUSTER AVAILABLE 问题 请问应该如何处理比较好？

### ISSUE THREAD

**Issue by darkice1** [yiding-he/hydrogen-ssdb#30]
长时间运行，有时会出现下面的报错（有可能几天出现一次）。ssdb 监测并没发现问题。  
建立方式  client = new SsdbClient(host,port,timeout, auth);
使用版本1.2.2

[2020-07-29 11:00:11]com.hyd.ssdb.SsdbNoClusterAvailableException: NO CLUSTER AVAILABLE
CAUSE:null
        at com.hyd.ssdb.sharding.ConsistentHashSharding.getClusterByKey(ConsistentHashSharding.java:281)
        at com.hyd.ssdb.conn.ConnectionPoolManager.getConnection(ConnectionPoolManager.java:77)
        at com.hyd.ssdb.AbstractClient.sendRequest(AbstractClient.java:116)
        at com.hyd.ssdb.AbstractClient.sendRequest(AbstractClient.java:94)
        at com.hyd.ssdb.SsdbClient.getBytes(SsdbClient.java:110)

**Comment by yiding-he** [comment]
@darkice1 能不能介绍下服务器的分布，有多少 Cluster，Cluster 是否存在主从，是否存在动态增减 Cluster 的操作，出现 `SsdbNoClusterAvailableException` 之前有过哪些与 hydrogen-ssdb 有关的异常，出现这个错误之后能否自行恢复？

因为从错误看是所有 Cluster 都失效才会报这个，在这之前应该会报出单个 Cluster 失效的 `SsdbNoServerAvailableException`。另一种可能是在运行时调用 removeCluster() 方法最终导致 Cluster 列表被清空。

**Comment by darkice1** [comment]
目前就一个单机 没有存在增加的情况  

另外 有时也会报 No cluster exists  
com.hyd.ssdb.SsdbNoClusterAvailableException: No cluster exists
CAUSE:null
        at com.hyd.ssdb.sharding.ConsistentHashSharding.autoExpand(ConsistentHashSharding.java:230)
        at com.hyd.ssdb.sharding.ConsistentHashSharding.clusterFailed(ConsistentHashSharding.java:209)
        at com.hyd.ssdb.conn.ConnectionPoolManager.getConnection(ConnectionPoolManager.java:97)
        at com.hyd.ssdb.AbstractClient.sendRequest(AbstractClient.java:116)
        at com.hyd.ssdb.AbstractClient.sendWriteRequest(AbstractClient.java:83)
        at com.hyd.ssdb.SsdbClient.setx(SsdbClient.java:134)

**Comment by yiding-he** [comment]
@darkice1 在这之前肯定会报一个 `SsdbSocketFailedException` 异常吧？当出现网络异常时，会打印三个 ERROR 日志：

1. `SsdbSocketFailedException` 异常日志，表示网络操作失败，此时会将 Server 从 Cluster 中标记为不可用，后台会有一个线程定时检查它；
1. 一行“Server unavailable: Server{host='xxx', port=xxx, master=xxx}”，输出具体是哪个 Server 不可用了；
1. 当所有的 Server 都不可用时，会尝试 autoExpand()，如果此时发现没有其他的 Cluster 可用，则会报 `SsdbNoClusterAvailableException`，就是你的第二个堆栈。

**Comment by darkice1** [comment]
我又过滤了一下日志  确实没有 sock 异常  感觉很诡异   目前就是单机没有走 cluster 

```
[root@jenkins allex]# more logs/realbigdata2db_20200729.log | grep ssdb
[2020-07-29 18:18:18]com.hyd.ssdb.SsdbNoClusterAvailableException: No cluster exists
        at com.hyd.ssdb.sharding.ConsistentHashSharding.autoExpand(ConsistentHashSharding.java:230)
        at com.hyd.ssdb.sharding.ConsistentHashSharding.clusterFailed(ConsistentHashSharding.java:209)
        at com.hyd.ssdb.conn.ConnectionPoolManager.getConnection(ConnectionPoolManager.java:97)
        at com.hyd.ssdb.AbstractClient.sendRequest(AbstractClient.java:116)
        at com.hyd.ssdb.AbstractClient.sendWriteRequest(AbstractClient.java:83)
        at com.hyd.ssdb.SsdbClient.setx(SsdbClient.java:134)
[2020-07-29 20:50:42]com.hyd.ssdb.SsdbNoClusterAvailableException: No cluster exists
        at com.hyd.ssdb.sharding.ConsistentHashSharding.autoExpand(ConsistentHashSharding.java:230)
        at com.hyd.ssdb.sharding.ConsistentHashSharding.clusterFailed(ConsistentHashSharding.java:209)
        at com.hyd.ssdb.conn.ConnectionPoolManager.getConnection(ConnectionPoolManager.java:97)
        at com.hyd.ssdb.AbstractClient.sendRequest(AbstractClient.java:116)
        at com.hyd.ssdb.AbstractClient.sendWriteRequest(AbstractClient.java:83)
        at com.hyd.ssdb.SsdbClient.setx(SsdbClient.java:134)
[2020-07-29 20:50:42]com.hyd.ssdb.SsdbNoClusterAvailableException: NO CLUSTER AVAILABLE
        at com.hyd.ssdb.sharding.ConsistentHashSharding.getClusterByKey(ConsistentHashSharding.java:281)
        at com.hyd.ssdb.conn.ConnectionPoolManager.getConnection(ConnectionPoolManager.java:77)
        at com.hyd.ssdb.AbstractClient.sendRequest(AbstractClient.java:116)
        at com.hyd.ssdb.AbstractClient.sendRequest(AbstractClient.java:94)
        at com.hyd.ssdb.SsdbClient.getBytes(SsdbClient.java:110)
```

**Comment by yiding-he** [comment]
@darkice1 怀疑有些错误信息没有输出。我优化了异常堆栈，建议取 1.2.3 分支最新代码编译一下部署上去，然后观察日志。
新的异常堆栈会包含最原始的错误原因，在日志中会一并打印出来，下面是一个例子：

```
11:32:06 [ERROR] c.h.s.ConnectionTest:41 - 
com.hyd.ssdb.SsdbNoClusterAvailableException: com.hyd.ssdb.SsdbNoServerAvailableException: No available master in cluster 'localhost:999'
	at com.hyd.ssdb.sharding.ConsistentHashSharding.autoExpand(ConsistentHashSharding.java:230) ~[classes/:na]
	at com.hyd.ssdb.sharding.ConsistentHashSharding.clusterFailed(ConsistentHashSharding.java:209) ~[classes/:na]
	at com.hyd.ssdb.conn.ConnectionPoolManager.getConnection(ConnectionPoolManager.java:96) ~[classes/:na]
	at com.hyd.ssdb.AbstractClient.sendRequest(AbstractClient.java:116) ~[classes/:na]
	at com.hyd.ssdb.AbstractClient.sendWriteRequest(AbstractClient.java:83) ~[classes/:na]
	at com.hyd.ssdb.SsdbClient.set(SsdbClient.java:128) ~[classes/:na]
	at com.hyd.ssdb.ConnectionTest.testConnectionFail(ConnectionTest.java:39) ~[test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_241]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_241]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_241]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_241]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.12.jar:4.12]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) [junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78) [junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137) [junit-4.12.jar:4.12]
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69) [junit-rt.jar:na]
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33) [junit-rt.jar:na]
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220) [junit-rt.jar:na]
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53) [junit-rt.jar:na]
Caused by: com.hyd.ssdb.SsdbNoServerAvailableException: No available master in cluster 'localhost:999'
	at com.hyd.ssdb.conf.Cluster.getMaster(Cluster.java:209) ~[classes/:na]
	at com.hyd.ssdb.conn.ConnectionPoolManager.pickServer(ConnectionPoolManager.java:127) ~[classes/:na]
	at com.hyd.ssdb.conn.ConnectionPoolManager.getConnection(ConnectionPoolManager.java:78) ~[classes/:na]
	... 26 common frames omitted
Caused by: com.hyd.ssdb.SsdbSocketFailedException: java.net.ConnectException: Connection refused: connect
	at com.hyd.ssdb.conn.Connection.<init>(Connection.java:49) ~[classes/:na]
	at com.hyd.ssdb.conn.Connection.<init>(Connection.java:31) ~[classes/:na]
	at com.hyd.ssdb.conn.ConnectionFactory.makeObject(ConnectionFactory.java:37) ~[classes/:na]
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:889) ~[commons-pool2-2.7.0.jar:2.7.0]
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:424) ~[commons-pool2-2.7.0.jar:2.7.0]
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:349) ~[commons-pool2-2.7.0.jar:2.7.0]
	at com.hyd.ssdb.conn.ConnectionPoolManager.getConnection(ConnectionPoolManager.java:81) ~[classes/:na]
	... 26 common frames omitted
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[na:1.8.0_241]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79) ~[na:1.8.0_241]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_241]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_241]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_241]
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[na:1.8.0_241]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_241]
	at java.net.Socket.connect(Socket.java:606) ~[na:1.8.0_241]
	at java.net.Socket.connect(Socket.java:555) ~[na:1.8.0_241]
	at java.net.Socket.<init>(Socket.java:451) ~[na:1.8.0_241]
	at java.net.Socket.<init>(Socket.java:228) ~[na:1.8.0_241]
	at com.hyd.ssdb.conn.Connection.<init>(Connection.java:37) ~[classes/:na]
	... 32 common frames omitted
```

**Comment by darkice1** [comment]
可以直接使用 MAVEN上的 1.2.3 吗？

**Comment by darkice1** [comment]
好的 我去试试

**Comment by darkice1** [comment]
您好 现在有报错如下 但是好像可以 catch 住不会有什么问题了。 如果我直接升级成 MAVEN 的版本可以吗？
```
[2020-08-03 09:00:27]com.hyd.ssdb.SsdbNoClusterAvailableException: com.hyd.ssdb.SsdbNoServerAvailableException: No available master in cluster '192.168.1.184:8888'
CAUSE:com.hyd.ssdb.SsdbNoServerAvailableException: No available master in cluster '192.168.1.184:8888'
        at com.hyd.ssdb.sharding.ConsistentHashSharding.autoExpand(ConsistentHashSharding.java:237)
        at com.hyd.ssdb.sharding.ConsistentHashSharding.clusterFailed(ConsistentHashSharding.java:216)
        at com.hyd.ssdb.conn.ConnectionPoolManager.getConnection(ConnectionPoolManager.java:103)
        at com.hyd.ssdb.AbstractClient.sendRequest(AbstractClient.java:116)
        at com.hyd.ssdb.AbstractClient.sendWriteRequest(AbstractClient.java:83)
        at com.hyd.ssdb.SsdbClient.setx(SsdbClient.java:150)
```

**Comment by yiding-he** [comment]
@darkice1 这个日志还是很奇怪啊，因为没看到 `Caused by`，我还要继续斟酌下，你先按你的想法处理吧。升级版本可以，但不保证能解决这个 issue。

**Comment by darkice1** [comment]
好的  我也在观察日志看看

**Comment by darkice1** [comment]
这次出现了一次卡住的情况不过看报错还是类似 没有caused by

```
[root@jenkins allex]# more logs/realbigdata2db_20200804.log  | grep ssdb
[2020-08-04 19:48:53]com.hyd.ssdb.SsdbNoClusterAvailableException: com.hyd.ssdb.SsdbNoServerAvailableException: Unable to find server in cluster '192.168.1.184:8888'
CAUSE:com.hyd.ssdb.SsdbNoServerAvailableException: Unable to find server in cluster '192.168.1.184:8888'
        at com.hyd.ssdb.sharding.ConsistentHashSharding.autoExpand(ConsistentHashSharding.java:237)
        at com.hyd.ssdb.sharding.ConsistentHashSharding.clusterFailed(ConsistentHashSharding.java:216)
        at com.hyd.ssdb.conn.ConnectionPoolManager.getConnection(ConnectionPoolManager.java:103)
        at com.hyd.ssdb.AbstractClient.sendRequest(AbstractClient.java:116)
        at com.hyd.ssdb.AbstractClient.sendRequest(AbstractClient.java:94)
        at com.hyd.ssdb.SsdbClient.getBytes(SsdbClient.java:117)
[2020-08-04 19:48:53]com.hyd.ssdb.SsdbNoClusterAvailableException: com.hyd.ssdb.SsdbNoClusterAvailableException: com.hyd.ssdb.SsdbNoServerAvailableException: Unable to find server in cluster '192.168.1.184:8888'
CAUSE:com.hyd.ssdb.SsdbNoClusterAvailableException: com.hyd.ssdb.SsdbNoServerAvailableException: Unable to find server in cluster '192.168.1.184:8888'
        at com.hyd.ssdb.sharding.ConsistentHashSharding.getClusterByKey(ConsistentHashSharding.java:288)
        at com.hyd.ssdb.conn.ConnectionPoolManager.getConnection(ConnectionPoolManager.java:84)
        at com.hyd.ssdb.AbstractClient.sendRequest(AbstractClient.java:116)
        at com.hyd.ssdb.AbstractClient.sendRequest(AbstractClient.java:94)
        at com.hyd.ssdb.SsdbClient.getBytes(SsdbClient.java:117)```

**Comment by darkice1** [comment]
会不会 SSDB 服务器超时之类的因素？

**Comment by yiding-he** [comment]
@darkice1 凡是网络出现问题，都不应该从日志中看不到记录。我在代码里面找不到原因，建议你把代码取下来，在合适的地方加上自己的日志，方便观察，关键是要了解**出问题之前到底发生过什么**。

**Comment by darkice1** [comment]
好的  
我再加一些记录 
之前代码很简单就是从 ssdb 获取数据 
ssdb 数据是另外一个程序从数据库直接序列化放入的

**Comment by yiding-he** [comment]
经确认，问题首先是出在用户 ssdb 服务负载过高导致客户端请求响应超时；此时 hydrogen-ssdb 没有在抛出的异常中正确的包含原始错误，故难以从日志中找到错误发生的实际原因。目前在 1.2.4 分支中修复了日志方面的问题，同时将超时时间配置改为 10 秒，效果有待进一步观察，同时建议用户对 ssdb 服务做适当的优化。

**Comment by darkice1** [comment]
已经解决 主要是 SSDD 服务器压力大问题导致
