### ISSUE TITLE
间歇性错误

### ISSUE THREAD

**Issue by QQxiaoyuyu** [yiding-he/hydrogen-ssdb#32]
com.hyd.ssdb.SsdbNoClusterAvailableException: NO CLUSTER AVAILABLE
CAUSE:null
        at com.hyd.ssdb.sharding.ConsistentHashSharding.getClusterByKey(ConsistentHashSharding.java:281)
        at com.hyd.ssdb.conn.ConnectionPoolManager.getConnection(ConnectionPoolManager.java:77)
        at com.hyd.ssdb.AbstractClient.sendRequest(AbstractClient.java:116)
        at com.hyd.ssdb.AbstractClient.sendRequest(AbstractClient.java:94)
        at com.hyd.ssdb.SsdbClient.multiGetBytes(SsdbClient.java:343)
        at tools.Ssdb.multiGetBytes(Ssdb.java:174)
        at runnable.SsdbQueue.run(SsdbQueue.java:105)
        at java.lang.Thread.run(Thread.java:748)

请问这个错误是什么原因呀  目前是一主一从，但是从没有请求，内存是6G，连接主的偶尔会报这个错误

**Comment by yiding-he** [comment]
Duplicate of #30

**Comment by yiding-he** [comment]
@QQxiaoyuyu 希望能参与到 #30 的解决当中来，若希望及时沟通，请加项目主页上的 QQ 群一起讨论！
